repos:
-   repo: https://github.com/pre-commit/pre-commit-hooks
    rev: v5.0.0
    hooks:
    -   id: trailing-whitespace
        args: [--markdown-linebreak-ext=md]
    -   id: end-of-file-fixer
    -   id: check-toml
    -   id: check-added-large-files
        args: ['--maxkb=1024']
    -   id: check-case-conflict
    -   id: mixed-line-ending
- repo: https://github.com/astral-sh/ruff-pre-commit
  rev: v0.8.3
  hooks:
    - id: ruff
      args: [ --fix ]
    - id: ruff-format

-   repo: https://github.com/pycqa/isort
    rev: 5.13.2
    hooks:
      - id: isort
        args: ["--profile", "black", "--filter-files"]
-   repo: https://github.com/psf/black
    rev: 24.10.0
    hooks:
      - id: black
-   repo: https://github.com/asottile/pyupgrade
    rev: v3.19.0
    hooks:
    -   id: pyupgrade
        args: [--py310-plus]
# -   repo: https://github.com/hhatto/autopep8
#     rev: v2.3.1
#     hooks:
#     -   id: autopep8
# -   repo: https://github.com/PyCQA/flake8
#     rev: "7.1.1"
#     hooks:
#       - id: flake8
#         additional_dependencies:
#           - flake8-comprehensions
#           - flake8-bugbear
#           - flake8-polyfill
#           - toml
#         exclude: docs\/.*
# -   repo: https://github.com/PyCQA/bandit
#     rev: '1.7.9'
#     hooks:
#     - id: bandit
#       args: ["-c", "pyproject.toml"]
#       additional_dependencies: ["bandit[toml]"]
